#![deny(unknown_lints)]
#![deny(renamed_and_removed_lints)]
#![forbid(unsafe_code)]
#![deny(deprecated)]
#![forbid(private_in_public)]
#![forbid(non_fmt_panics)]
#![deny(unreachable_code)]
#![deny(unreachable_patterns)]
#![forbid(unused_doc_comments)]
#![forbid(unused_must_use)]
#![deny(while_true)]
#![deny(unused_parens)]
#![deny(redundant_semicolons)]
#![deny(non_ascii_idents)]
#![deny(confusable_idents)]
#![warn(missing_docs)]
#![warn(clippy::missing_docs_in_private_items)]
#![warn(clippy::cargo_common_metadata)]
#![warn(rustdoc::missing_crate_level_docs)]
#![warn(missing_debug_implementations)]

#![doc = include_str!("../README.md")]

use thiserror::Error;

use tracing::instrument;

/// Error type for redmine_api
#[derive(Debug, Error)]
pub enum Error {
    /// This variant is just here as a placeholder to show the syntax
    #[error("error type not implemented yet")]
    NotImplementedError,
}

/// The main behaviour of the binary should go here
#[instrument]
async fn example_fun() -> Result<(), Error> {
    tracing::debug!("{:#?}", "Hello, World!");
    Ok(())
}

#[cfg(test)]
mod test {
    use super::*;
    use pretty_assertions::{assert_eq, assert_ne};

    /// Tests if the author concerned themselves with tests at all.
    /// This is mainly generated by the project templates so tests can
    /// not be completely ignored
    #[test]
    fn test_added_tests() {
        assert!(false);
    }
}
